### ISSUE TITLE
Implement async::sequence<A: Async, I: IntoIterator<Item=A>>(i: I) -> Stream<A::Value, A::Error>

### ISSUE THREAD

**Issue by carllerche** [carllerche/syncbox#11]
Hopefully I got the type signature right...

The general idea would be to take a set of async values and return a stream representing the supplied values in order of completion.

/cc @hoverbear

**Comment by reem** [comment]
Type signature looks right to me.

**Comment by Hoverbear** [comment]
That signature looks right to me, too!

**Comment by carllerche** [comment]
This is done: https://github.com/carllerche/syncbox/blob/master/src/util/async/sequence.rs

**Comment by Hoverbear** [comment]
@carllerche Awesome! Thank you!
