### ISSUE TITLE
Should Async::poll be considered as registering interest?

### ISSUE THREAD

**Issue by carllerche** [carllerche/syncbox#14]
On one hand, it is attempting to observe the data, on the other, if the data isn't available, it won't return the data...

**Comment by Hoverbear** [comment]
`poll` may be used to evaluate which decision to make in control flow, and does not necessarily imply there is a desire to immediately act on the value should it be present.

**Comment by carllerche** [comment]
I think you are probably right. I'm going to close this as I think the answer is no.
